apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jira-ingress-external
  annotations:
    certmanager.k8s.io/acme-challenge-type: http01
    certmanager.k8s.io/enabled: "true"
    ingress.kubernetes.io/affinity: cookie
    ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/backend-protocol: "HTTPS"
    ingress.kubernetes.io/session-cookie-name: ingress
    ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/whitelist-source-range: "
      {{ file .IP_WHITELIST_FILE }}
    "
    kubernetes.io/ingress.class: nginx-external
spec:
  rules:
  - host: {{ .JIRA_DNS_NAME }}
    http:
      paths:
      - backend:
          serviceName: jira
          servicePort: https
        path: /
  tls:
  - hosts:
    - {{ .JIRA_DNS_NAME }}
    # @NOTE: this is the name of the kubernetes secret to create in your namespace
    secretName: jira-tls