kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jira-data
  annotations:
    volume.beta.kubernetes.io/storage-class: {{ .STORAGE_CLASS }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .JIRA_DATA_VOLUME_SIZE }}
